### PR TITLE
Ma feature login

### PR DESCRIPTION
**Pull request by mallman1**
Adds log in functionality, force users to log in in order to create a property or post a review. Forces users to use Facebook to log in.

### CODE REVIEW

**Comment by disciple520** [comment]
{
   "error": {
      "message": "Invalid redirect_uri: Given URL is not allowed by the Application configuration",
      "type": "OAuthException",
      "code": 191
   }
}

Here is the error I get. Where do I need to change the code to work with my machine? I'm not using Nitrous.

**Comment by mallman1** [comment]
I dont think it's something that you can fix, it's because my facebook configuration is set to my specific nitrous box. I don't know how we would resolve that.

**Comment by mallman1** [comment]
Try now, I changed it to http://localhost:3000

**Comment by disciple520** [comment]
screenshot 2015-04-28 20 14 03

**Comment by mallman1** [comment]
What's your facebook name? I can try adding it to the registered test users

**Comment by disciple520** [comment]
woods.jerry@gmail.com

**Comment by mallman1** [comment]
I added you, try it now.

**Comment by disciple520** [comment]
Wow. That works really, really well man. Good job. 
+11

**Comment by mallman1** [comment]
Awesome.

**Pull request merged**
