### PR TITLE
Removed the Delete review button and lined up the ratings label

### PR DESCRIPTION
**Pull request by cknapp811**

### CODE REVIEW

**Comment by mkaempf1** [comment]
+1

**Comment by cknapp811** [comment]
Yea Its still going to be named that in the db i just figured it made more sense changing the label

**Comment by disciple520** [comment]
Hey so when I clone your repo and run it my labels are not lined up. This is what it looks like no matter how I resize the screen. 

screenshot 2015-04-22 15 49 40


Does it look different on yours?

**Comment by bhogancvtc** [comment]
It would be wise to change the column name with a migration.

**Comment by AdamPapierniak** [comment]
I cloned yours and got the same thing as Jerry. I changed the right px amount to 52 and it looked like it lined up. I'm not sure how to push that change to anything except your master though. If you change it and it looks ok on your screen it would probably be easier for you just to push your master again.

**Comment by cknapp811** [comment]
Hmm that's really weird I'll fix it up and try it again

**Pull request merged**
